const commonCode = [
	{
		cd: "OV001",
		label: "매출",
	},
	{
		cd: "OV002",
		label: "주문건수",
	},
	{
		cd: "OV003",
		label: "주문당 결제금액",
	},
	{
		cd: "OV004",
		label: "방문자수",
	},
	{
		cd: "OV005",
		label: "신규회원",
	},
	{
		cd: "OV006",
		label: "비활성 회원",
	},
	{
		cd: "OV007",
		label: "누적 회원수",
	},
	{
		cd: "OV008",
		label: "누적 주문금액",
	},
	{
		cd: "OV009",
		label: "평균 주문금액",
	},
	{
		cd: "OV010",
		label: "클럽머니",
	},
	{
		cd: "OV011",
		label: "좋아요",
	},
	{
		cd: "LV001",
		label: "Silver",
	},
	{
		cd: "LV002",
		label: "Gold",
	},
	{
		cd: "LV003",
		label: "VIP",
	},
	{
		cd: "UT001",
		label: "활성회원",
	},
	{
		cd: "UT002",
		label: "정지회원",
	},
	{
		cd: "UT003",
		label: "비활성회원",
	},
	{
		cd: "ST001",
		label: "결제대기",
	},
	{
		cd: "ST002",
		label: "상품준비중",
	},
	{
		cd: "ST003",
		label: "배송중",
	},
	{
		cd: "ST004",
		label: "도착",
	},
	{
		cd: "ST005",
		label: "반품처리중",
	},
	{
		cd: "ST006",
		label: "반품완료",
	},
	{
		cd: "ST007",
		label: "결제완료",
	},
	{
		cd: "PY001",
		label: "주문금액",
	},
	{
		cd: "PY002",
		label: "배송비",
	},
	{
		cd: "PY003",
		label: "할인금액",
	},
	{
		cd: "PM001",
		label: "신용/체크카드",
	},
	{
		cd: "PM002",
		label: "현대카드",
	},
	{
		cd: "PM003",
		label: "네이버페이",
	},
	{
		cd: "PM004",
		label: "토스",
	},
	{
		cd: "PM005",
		label: "카카오페이",
	},
	{
		cd: "PM006",
		label: "페이코",
	},
	{
		cd: "PM007",
		label: "무통장입금",
	},
	{
		cd: "PM008",
		label: "휴대폰결제",
	},
	{ label: "Afghanistan", cd: "AF" },
	{ label: "Aland Islands", cd: "AX" },
	{ label: "Albania", cd: "AL" },
	{ label: "Algeria", cd: "DZ" },
	{ label: "American Samoa", cd: "AS" },
	{ label: "Andorra", cd: "AD" },
	{ label: "Angola", cd: "AO" },
	{ label: "Anguilla", cd: "AI" },
	{ label: "Antarctica", cd: "AQ" },
	{ label: "Antigua and Barbuda", cd: "AG" },
	{ label: "Argentina", cd: "AR" },
	{ label: "Armenia", cd: "AM" },
	{ label: "Aruba", cd: "AW" },
	{ label: "Australia (Australia)", cd: "AU" },
	{ label: "Austria", cd: "AT" },
	{ label: "Azerbaijan", cd: "AZ" },
	{ label: "Bahamas", cd: "BS" },
	{ label: "Bahrain", cd: "BH" },
	{ label: "Bangladesh", cd: "BD" },
	{ label: "Barbados", cd: "BB" },
	{ label: "Belarus", cd: "BY" },
	{ label: "Belgium", cd: "BE" },
	{ label: "Belize", cd: "BZ" },
	{ label: "Benin", cd: "BJ" },
	{ label: "Bermuda shorts", cd: "BM" },
	{ label: "Bolivia", cd: "BO" },
	{ label: "Bosnia and Herzegovina", cd: "BA" },
	{ label: "Botswana", cd: "BW" },
	{ label: "Bouvet Island", cd: "BV" },
	{ label: "Brazil", cd: "BR" },
	{ label: "British Indian Ocean Territory", cd: "IO" },
	{ label: "British Virgin Islands", cd: "VG" },
	{ label: "Brunei", cd: "BN" },
	{ label: "Bulgaria", cd: "BG" },
	{ label: "Burkina Faso", cd: "BF" },
	{ label: "Burundi", cd: "BI" },
	{ label: "butane", cd: "BT" },
	{ label: "Cambodia", cd: "KH" },
	{ label: "Cameroon", cd: "CM" },
	{ label: "Canada", cd: "CA" },
	{ label: "Cape Verde", cd: "CV" },
	{ label: "catarrh", cd: "QA" },
	{ label: "Cayman Islands", cd: "KY" },
	{ label: "Central African Republic", cd: "CF" },
	{ label: "Chad", cd: "TD" },
	{ label: "Chile", cd: "CL" },
	{ label: "China", cd: "CN" },
	{ label: "Christmas Island", cd: "CX" },
	{ label: "Cocos Islands", cd: "CC" },
	{ label: "Columbia", cd: "CO" },
	{ label: "Comoros", cd: "KM" },
	{ label: "Cook islands", cd: "CK" },
	{ label: "Costa Rica", cd: "CR" },
	{ label: "Croatia", cd: "HR" },
	{ label: "Cuba", cd: "CU" },
	{ label: "Cyprus", cd: "CY" },
	{ label: "Czech Republic", cd: "CZ" },
	{ label: "Democratic Republic of the Congo", cd: "CD" },
	{ label: "Denmark", cd: "DK" },
	{ label: "Djibouti", cd: "DJ" },
	{ label: "Dominican", cd: "DM" },
	{ label: "Dominican Republic", cd: "DO" },
	{ label: "East Timor", cd: "TL" },
	{ label: "Ecuador", cd: "EC" },
	{ label: "Egypt", cd: "EG" },
	{ label: "El Salvador", cd: "SV" },
	{ label: "England", cd: "GB" },
	{ label: "Equatorial Guinea", cd: "GQ" },
	{ label: "Eritrea", cd: "ER" },
	{ label: "Estonia", cd: "EE" },
	{ label: "Ethiopia", cd: "ET" },
	{ label: "Falkland Islands", cd: "FK" },
	{ label: "Faroe Islands", cd: "FO" },
	{ label: "Federation of Micronesia", cd: "FM" },
	{ label: "Finland", cd: "FI" },
	{ label: "France", cd: "FR" },
	{ label: "French Guiana", cd: "GF" },
	{ label: "French Polynesia", cd: "PF" },
	{ label: "French Southern and Antarctic Region", cd: "TF" },
	{ label: "Gabon", cd: "GA" },
	{ label: "Gambia", cd: "GM" },
	{ label: "Georgia", cd: "GE" },
	{ label: "Germany", cd: "DE" },
	{ label: "Ghana", cd: "GH" },
	{ label: "Gibraltar", cd: "GI" },
	{ label: "Greece", cd: "GR" },
	{ label: "Greenland", cd: "GL" },
	{ label: "Guadeloupe", cd: "GP" },
	{ label: "Guam", cd: "GU" },
	{ label: "Guatemala", cd: "GT" },
	{ label: "Guinea", cd: "GN" },
	{ label: "Guinea-Bissau", cd: "GW" },
	{ label: "Guyana", cd: "GY" },
	{ label: "Haiti", cd: "HT" },
	{ label: "Heard and McDonald Islands", cd: "HM" },
	{ label: "Honduras", cd: "HN" },
	{ label: "Hong Kong", cd: "HK" },
	{ label: "Hungary", cd: "HU" },
	{ label: "Iceland", cd: "IS" },
	{ label: "India", cd: "IN" },
	{ label: "Indonesia", cd: "ID" },
	{ label: "Iran", cd: "IR" },
	{ label: "Iraq", cd: "IQ" },
	{ label: "Ireland", cd: "IE" },
	{ label: "Israel", cd: "IL" },
	{ label: "Italy", cd: "IT" },
	{ label: "Ivory Coast", cd: "CI" },
	{ label: "Jamaica", cd: "JM" },
	{ label: "Japan", cd: "JP" },
	{ label: "Jordan", cd: "JO" },
	{ label: "Kazakhstan", cd: "KZ" },
	{ label: "Kenya", cd: "KE" },
	{ label: "Kiribati", cd: "KI" },
	{ label: "Kuwait", cd: "KW" },
	{ label: "Kyrgyzstan", cd: "KG" },
	{ label: "Laos", cd: "LA" },
	{ label: "Latvia", cd: "LV" },
	{ label: "Lebanon", cd: "LB" },
	{ label: "Lesotho", cd: "LS" },
	{ label: "Liberia", cd: "LR" },
	{ label: "Libya", cd: "LY" },
	{ label: "Liechtenstein", cd: "LI" },
	{ label: "Lithuania", cd: "LT" },
	{ label: "Luxembourg", cd: "LU" },
	{ label: "Macau", cd: "MO" },
	{ label: "Madagascar", cd: "MG" },
	{ label: "Malawi", cd: "MW" },
	{ label: "Malaysia", cd: "MY" },
	{ label: "Maldive Islands", cd: "MV" },
	{ label: "Mali", cd: "ML" },
	{ label: "Malta", cd: "MT" },
	{ label: "Marshall Islands", cd: "MH" },
	{ label: "Martinique", cd: "MQ" },
	{ label: "Mauritania", cd: "MR" },
	{ label: "Mauritius", cd: "MU" },
	{ label: "Mayotte", cd: "YT" },
	{ label: "Mexico", cd: "MX" },
	{ label: "Moldova", cd: "MD" },
	{ label: "Monaco", cd: "MC" },
	{ label: "Mongolia", cd: "MN" },
	{ label: "Montserrat", cd: "MS" },
	{ label: "Morocco", cd: "MA" },
	{ label: "Mozambique", cd: "MZ" },
	{ label: "Myanmar", cd: "MM" },
	{ label: "Namibia", cd: "NA" },
	{ label: "Nauru", cd: "NR" },
	{ label: "Nepal", cd: "NP" },
	{ label: "Netherlands", cd: "NL" },
	{ label: "Netherlands Antilles", cd: "AN" },
	{ label: "New Zealand", cd: "NZ" },
	{ label: "Nicaragua", cd: "NI" },
	{ label: "Niger", cd: "NE" },
	{ label: "Nigeria", cd: "NG" },
	{ label: "Niue", cd: "NU" },
	{ label: "Norfolk Island", cd: "NF" },
	{ label: "Northern Mariana Islands", cd: "MP" },
	{ label: "Norway", cd: "NO" },
	{ label: "Nouvelle Caledonia", cd: "NC" },
	{ label: "Oman", cd: "OM" },
	{ label: "Pakistan", cd: "PK" },
	{ label: "Palau", cd: "PW" },
	{ label: "Palestine", cd: "PS" },
	{ label: "Panama", cd: "PA" },
	{ label: "Papua New Guinea", cd: "PG" },
	{ label: "Paraguay", cd: "PY" },
	{ label: "Peru", cd: "PE" },
	{ label: "Philippines", cd: "PH" },
	{ label: "Pitcairn Islands", cd: "PN" },
	{ label: "Poland", cd: "PL" },
	{ label: "Portugal", cd: "PT" },
	{ label: "Puerto Rico", cd: "PR" },
	{ label: "Republic of China (Taiwan)", cd: "TW" },
	{ label: "Republic of Korea (국내 배송)", cd: "KR" },
	{ label: "Republic of Macedonia", cd: "MK" },
	{ label: "Republic of South Africa", cd: "ZA" },
	{ label: "Republic of the Congo", cd: "CG" },
	{ label: "Reunion", cd: "RE" },
	{ label: "Romania", cd: "RO" },
	{ label: "Russia", cd: "RU" },
	{ label: "Rwanda", cd: "RW" },
	{ label: "Saint Kitts and Nevis", cd: "KN" },
	{ label: "Saint Lucia", cd: "LC" },
	{ label: "Saint Pierre Miquelon", cd: "PM" },
	{ label: "Saint Vincent and the Grenadines", cd: "VC" },
	{ label: "Samoa", cd: "WS" },
	{ label: "San Marino", cd: "SM" },
	{ label: "Sao Tome and Principe", cd: "ST" },
	{ label: "Saudi Arabia", cd: "SA" },
	{ label: "sebum", cd: "FJ" },
	{ label: "Senegal", cd: "SN" },
	{ label: "Serbia and Montenegro", cd: "CS" },
	{ label: "Seychelles", cd: "SC" },
	{ label: "Sierra Leone", cd: "SL" },
	{ label: "Singapore", cd: "SG" },
	{ label: "Slovakia", cd: "SK" },
	{ label: "Slovenian", cd: "SI" },
	{ label: "Solomon Islands", cd: "SB" },
	{ label: "Somalia", cd: "SO" },
	{ label: "South Georgia and the South Sandwich Islands", cd: "GS" },
	{ label: "Spain", cd: "ES" },
	{ label: "Sri Lanka", cd: "LK" },
	{ label: "St Helena", cd: "SH" },
	{ label: "surname", cd: "SR" },
	{ label: "Svalbard Jan Mayen", cd: "SJ" },
	{ label: "Swaziland", cd: "SZ" },
	{ label: "Sweden", cd: "SE" },
	{ label: "Swiss", cd: "CH" },
	{ label: "Syria", cd: "SY" },
	{ label: "Tajikistan", cd: "TJ" },
	{ label: "Tanzania", cd: "TZ" },
	{ label: "The Democratic People's Republic of Korea", cd: "KP" },
	{ label: "tie", cd: "TH" },
	{ label: "Togo", cd: "TG" },
	{ label: "Tokelau Islands", cd: "TK" },
	{ label: "Tonga", cd: "TO" },
	{ label: "Trinidad and Tobago", cd: "TT" },
	{ label: "Tunisia", cd: "TN" },
	{ label: "Turkey", cd: "TR" },
	{ label: "Turkmenistan", cd: "TM" },
	{ label: "Turks and Caicos Islands", cd: "TC" },
	{ label: "Tuvalu", cd: "TV" },
	{ label: "U.S. minor system", cd: "UM" },
	{ label: "U.S. Virgin Islands", cd: "VI" },
	{ label: "Uganda", cd: "UG" },
	{ label: "Ukraine", cd: "UA" },
	{ label: "United Arab Emirates", cd: "AE" },
	{ label: "Uruguay", cd: "UY" },
	{ label: "USA", cd: "US" },
	{ label: "Uzbekistan", cd: "UZ" },
	{ label: "Vanuatu", cd: "VU" },
	{ label: "Vatican City", cd: "VA" },
	{ label: "Venezuela", cd: "VE" },
	{ label: "Vietnam", cd: "VN" },
	{ label: "Wagner grenadines", cd: "GD" },
	{ label: "Wallis and Futuna", cd: "WF" },
	{ label: "Way", cd: "SD" },
	{ label: "Western Sahara", cd: "EH" },
	{ label: "Yemen", cd: "YE" },
	{ label: "Zambia", cd: "ZM" },
	{ label: "Zimbabwe", cd: "ZW" },
];

export default {
	init(Vue) {
		Vue.filter("addCommas", (val) => {
			if (!val && val !== 0) return "";
			return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
		});

		Vue.filter("codeLabel", (val) => {
			if (!val && val !== 0) return "";
			const codeObj = commonCode.filter((item) => item.cd === val)[0];
			if (!codeObj) return "";
			return codeObj.label;
		});
	},
};
